language: r

warnings_are_errors: true

sudo: required

apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev
 
notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat
